version: "3"
services:
    practice-nonrelational:
        container_name: "practice-nonrelational"
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - db
        restart: always
    db:
        container_name: "mongo"
        image: mongo
        ports:
            - "27017:27017"
        restart: always
